### ISSUE TITLE
Handle hackage metadata revisions

### ISSUE THREAD

**Issue by gbaz** [gentoo-haskell/hackport#30] opened 2017-09-20 14:23 UTC
As per https://github.com/haskell/hackage-server/issues/611 it seems like hackport isn't picking up metadata revisions?

**Comment by trofi** [comment] 2017-09-20 19:30
Can you be a bit more precise what you would like to see added to hackport?

**Comment by gbaz** [comment] 2017-09-20 20:50
This isn't my issue originally -- trying to sort out the request on the linked ticket. As I understand it the issue is `hackport merge` which creates ebuilds from hackage packages. It apparently builds them based on the cabal file in the tarball. Due to hackage revisions, that file may have been updated, and will need to be fetched separately. @hvr can suggest the easiest mechanism to get the latest revision.

**Comment by trofi** [comment] 2017-09-20 21:58
hackport generates `.ebuild` files based on hackage index you have downloaded with hackport update.
The problem is `emerge` at merge time knows nothing about patched `.cabal` file.

I usually add `src_prepare()` into ebuild with a bunch of `cabal_chdeps` dependency loosenings
to make cabal resolver to pick correct dependencies.

What would you like hackport to do in this case? There is a few options here (not sure which ones are easier to implement). For example, hackport could unpack `.cabal` file from hackage index tarball and generate piece f code to override default .cabal in src_prepare().

**Comment by gbaz** [comment] 2017-09-20 22:04
Again, hvr is more expert than me. But my sense is that hackport could use the new index-01 file, and manage fetching and interacting with it using the hackage-security package (https://hackage.haskell.org/package/hackage-security-0.5.2.2/docs/Hackage-Security-Client.html). The index-01 has all cabal revisions included, so working with that should ensure that the latest one is always used.

This should help minimize the work by hackport users in mucking with dependencies, since now hackport can pick up on those changes directly...

**Comment by gbaz** [comment] 2017-09-20 22:07
(in fact, i see hackage-security is already a submodule in the src tree, so maybe its just a matter of changing its usage slightly?)

**Comment by gbaz** [comment] 2017-09-21 03:47
Revisions can be and often are author-provided. This is just additional metadata that can help tooling to understand new information about constraints as it becomes available. In fact, packages aren't "messed with" at all and are left entirely untouched! That's why there's this issue at all -- tooling that wants to take advantage of this new metadata needs to be taught about it.

**Comment by trofi** [comment] 2017-09-21 08:29
Can you provide exact package version and hackport command and show where you
would like output to be different?

**Comment by gbaz** [comment] 2017-12-28 21:34
Just got around to this and it appears to be fixed somewhere already in HEAD by the changes for compat with cabal and hackage security. In particular I tested hasmin and got the following line

            >=dev-haskell/bifunctors-5.4:=[profile?] <dev-haskell/bifunctors-5.6:=[profile?]

This reflects correctly the changes from r1 here: http://hackage.haskell.org/package/hasmin-1.0.1/revisions/

As such, closing.

**Comment by trofi** [comment] 2017-12-28 21:51
I believe it was fixed by https://github.com/gentoo-haskell/hackport/commit/5256dd4d37814ac66870499431a1287620d36d17 which shifted from http-based to https-based index fetch.

It was surprising to see some packages were not available in the http-based index.
And the difference is not just revisions handling (those worked for a long while). It's the difference in versions available:

```
$ cabal list haddock-library
* haddock-library
    Synopsis: Library exposing some functionality of Haddock.
    Default available version: 1.4.3
    Installed versions: 1.4.2
    Homepage: http://www.haskell.org/haddock/
    License:  BSD3
```

```
$ hackport status --from-hackage dev-haskell/haddock-library
Green: package in portage and overlay are the same
Yellow: package in portage and overlay differs
Red: package only exist in the overlay
Magenta: package only exist in the portage tree
Cyan: package only exist on hackage
1 dev-haskell/haddock-library 1.1.1 1.2.1 1.4.2 1.4.3 1.4.4 1.4.5
```

Note the difference for latest version available for `cabal-install` (from `1.24` `Cabal` branch) and `hackport` (`Cabal` `HEAD`)

**Comment by gbaz** [comment] 2017-12-28 23:16
There should be no difference in the _same_ indexes from http or https. However, the move from the 00-index to the 01-index is significant. The latter contains revisions, the former does not. Furthermore, the latter contains cabal 2.0 syntax files while the former does not, for backwards-compat with earlier cabals that cannot handle such syntax.

Now that the 01-index format is set, and now that we have a direct forward-compat mechanism for Cabal to know how to disregard files with newer version requirements, this should be the last time this particular sort of "growing pain" weirdness occurs.

**Comment by trofi** [comment] 2018-01-21 17:13
It looks like you are touching multiple issues at the same time and using different terminology from what I expect.

#### 0. On indexes
> There should be no difference in the same indexes from `http://` or `https://`

It does not seem like `01` index is accessible over `http://` at all:
- `http://hackage.haskell.org/01-index.tar.gz` is not a working URL

Thus my inference `https://` is not orthogonal to `01` index format. And the very change that "fixes" use of new index specifically switches to `SecureRepo` (and switch from `00` to `01` format happens deeper in `Cabal` client code): https://github.com/gentoo-haskell/hackport/commit/5256dd4d37814ac66870499431a1287620d36d17

#### 1. On revisions
>  The latter contains revisions, the former does not.

`00-index.tar` clearly contains revbumped `.cabal` files:
```
$ tar xf 00-index.tar 
$ fgrep -R x-revision . | wc -l
10017
```
and it had been an annoyance for quite a while because `gentoo` needs to retroactively repackage "revisioned" packages. It's not something that appeared in `01` index. Unless you mean a different thing.

**Comment by hvr** [comment] 2018-01-21 19:10
I'm not sure what you mean by not accessible; for me it seems to work:

```
$ wget --debug http://hackage.haskell.org/01-index.tar.gz
DEBUG output created by Wget 1.17.1 on linux-gnu.

Reading HSTS entries from /home/hvr/.wget-hsts
URI encoding = ‘UTF-8’
--2018-01-21 20:03:47--  http://hackage.haskell.org/01-index.tar.gz
Host ‘hackage.haskell.org’ has not issued a general basic challenge.
Resolving hackage.haskell.org (hackage.haskell.org)... 151.101.0.68, 151.101.192.68, 151.101.128.68, ...
Caching hackage.haskell.org => 151.101.0.68 151.101.192.68 151.101.128.68 151.101.64.68
Connecting to hackage.haskell.org (hackage.haskell.org)|151.101.0.68|:80... connected.
Created socket 3.
Releasing 0x0000557aa7e8fd50 (new refcount 1).

---request begin---
GET /01-index.tar.gz HTTP/1.1
User-Agent: Wget/1.17.1 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: hackage.haskell.org
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Content-Type: application/x-gzip
Accept-Ranges: bytes
Cache-Control: public, no-transform, max-age=300
Content-MD5: XiX2rgSFAR0zLFCt3WKT5g==
ETag: "5e25f6ae0485011d332c50addd6293e6"
Last-modified: Sun, 21 Jan 2018 18:48:18 GMT
Content-Length: 65381365
Accept-Ranges: bytes
Date: Sun, 21 Jan 2018 19:03:47 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-hhn1530-HHN
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1516561428.621649,VS0,VE124

---response end---
200 OK
Registered socket 3 for persistent reuse.
Length: 65381365 (62M) [application/x-gzip]
Saving to: ‘01-index.tar.gz’

01-index.tar.gz                                                        100%[============================================================================================================================================================================>]  62.35M  8.75MB/s    in 7.7s    

2018-01-21 20:03:55 (8.05 MB/s) - ‘01-index.tar.gz’ saved [65381365/65381365]

```


----

As for revisions; I think @gbaz meant to say that the `00-index.tar` index contains only the latest revisions (rather than all revisions) for each (package-name,package-version) entry, whereas `01-index.tar` contains all revisions (and in addition to containing cabal 2.0+ format files); thus the `01-index.tar` file contains a strict superset of the information provided by the `00-index.tar` format; or put differently, you can construct a `00-index.tar` from a `01-index.tar`, but not the other way around.

**Comment by trofi** [comment] 2018-01-21 19:26
I confused output of `wget -c http://` (resume download gets `bad request` when file is present on disk). Thanks for double-checking!

**Comment by l29ah** [comment] 2021-05-27 18:23
hackport still does nothing about cabal revisions, reopen plz.

**Comment by hololeap** [comment] 2022-03-01 21:19
Having `hackport merge` auto-generate this stuff in the ebuild seems like it would be a fairly easy solution:

https://github.com/gentoo-haskell/gentoo-haskell/wiki/Useful-snippets#use-upstream-cabal-revision-from-hackage
## Use upstream `cabal` revision from Hackage
```bash
HACKAGE_REV="3" # Change this to the latest revision number
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz
	https://hackage.haskell.org/package/${P}/revision/${HACKAGE_REV}.cabal -> ${PF}.cabal"

BDEPEND="app-text/dos2unix"

src_prepare() {
	# pull revised cabal from upstream
	cp "${DISTDIR}/${PF}.cabal" "${S}/${PN}.cabal" || die

	# Convert to unix line endings
	dos2unix "${S}/${PN}.cabal" || die

	# Apply patches *after* pulling the revised cabal
	default
}
```

### Variant that uses `${MY_P}`
```bash
HACKAGE_REV="2" # Change this to the latest revision number
SRC_URI="https://hackage.haskell.org/package/${MY_P}/${MY_P}.tar.gz
	https://hackage.haskell.org/package/${MY_P}/revision/${HACKAGE_REV}.cabal -> ${PF}.cabal"

BDEPEND="app-text/dos2unix"

src_prepare() {
	# pull revised cabal from upstream
	cp "${DISTDIR}/${PF}.cabal" "${S}/${MY_PN}.cabal" || die

	# Convert to unix line endings
	dos2unix "${S}/${MY_PN}.cabal" || die

	# Apply patches *after* pulling the revised cabal
	default
}
```

**Comment by hololeap** [comment] 2022-03-01 21:22
It looks to me like `hackport merge` already generates dependencies that reflect the latest Hackage revision, but we just need to pull the updated `.cabal` file in before building.

**Comment by solpeth** [comment] 2022-03-02 09:50
> I'm convinced that `hackport merge` already has some knowledge of the Hackage revisions, as the dependencies in the generated ebuild are based on the latest revision on Hackage.

I don't know if it has the information to determine which revision a particular package is up to (I believe it just pulls the index, which has the latest revisions, but I am unsure if it differentiates them per-package or just knows to pull the latest revision), but that would be great if you found (or I, if I find the time) that it did. Then we could use that information to automate the first `HACKAGE_REVISION=x` number. If not, I say we default to `0` and then adjust as needed.

> The only thing that is not currently automated is generating the parts of the ebuild which fetch the `.cabal` file and copy it over as a part of `src_prepare`. I've used those "snippets" I referenced many many times and have run into no problems, so I'm certain that they could be safely added to the generated ebuild.

Let's try it. I can get to implementation in the next few weeks unless you want to do it sooner.

It would be nicer (imo) to move this boilerplate into the eclass, out of sight and away from accidental damage, but that shouldn't hold us up from testing the usefulness of having hackport generate this boilerplate by default. We can adjust hackport's ebuild output later if we move the boilerplate to the eclass.

**Closed** 2022-07-19 05:23 UTC
Labels: feature
