### ISSUE TITLE
Handle multiple test-suite stanzas

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/hackport#81] opened 2021-01-13 21:27 UTC
This cabal file has multiple `test-suite` stanzas and only the dependencies from one are being added to the generated ebuild.

https://hackage.haskell.org/package/postgresql-simple-0.6.4/postgresql-simple.cabal :
```
test-suite inspection
  if !impl(ghc >=8.0)
    buildable: False

  default-language: Haskell2010
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Inspection.hs
  build-depends:
      base
    , inspection-testing  >=0.4.1.1 && <0.5
    , postgresql-libpq
    , postgresql-simple
    , tasty
    , tasty-hunit

test-suite test
  default-language:   Haskell2010
  type:               exitcode-stdio-1.0
  hs-source-dirs:     test
  main-is:            Main.hs
  ...
```

`inspection-testing` was not added to the ebuild. This ends up with a failure during the configure phase, since cabal wants `inspection-testing` to be installed.

**Comment by trofi** [comment] 2021-01-14 06:53
The problem is not in multiple stanzas, but in a version-specific guard:

```
  if !impl(ghc >=8.0)
    buildable: False
```

`hackport` starts off with `ghc-7` and settles on an older ghc version with subset of tests disabled.

**Comment by trofi** [comment] 2021-01-14 06:54
I think it's a duplicate of https://github.com/gentoo-haskell/hackport/issues/80

**Closed** 2021-01-14 07:14 UTC
